#http port
server:
  port:8080

spring:
  profiles:
    include: db
  
  #thymeleaf auto refresh
  thymeleaf:
    cache: false

  servlet:
    multipart:
      location: c:\\devs\\input
      max-file-size: 40MB
      max-request-size: 50MB

files:
  dailyPlans:
    location: c:\\devs\\files\\dailyPlans
  boards:
    location: c:\\devs\\files\\boards

# mybatis mapping
# mapper.xml
mybatis:
  type-aliases-package: com.example.spring.myapp.model
  # mapper.xml location
  mapper-locations: /mybatis/mapgiper/**/*.xml